### ISSUE TITLE
Add new alternateIdentifier to match SBN schema

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#102]
**Is your feature request related to a problem? Please describe.**
Per SBN schema for submissions to datacite, we should look into adding an additional alternateIdentifier for explicitly defining the PDS ID.

NOTE: This is not currently possible with OSTI. This is dependent upon switching over to DataCite.

**Additional Details**
See https://sbnwiki.astro.umd.edu/wiki/DataCite_Schema#.3CalternateIdentifiers.3E for how SBN uses alternateIdentifiers and maps them to PDS4 LIDVIDs. We want to do the same in the DOI Service

**Applicable requirements**
:unicorn: #16

**Comment by jordanpadams** [comment]
@collinss-jpl how are we currently putting the PDS LIDVID into the DOI metadata? From the info above, we should use this in `alternateIdentifier`

**Comment by jordanpadams** [comment]
Deferring to B12.1. Enhancement to DOI Service. Not requirement.

**Comment by jordanpadams** [comment]
Deferring from this sprint for other more high priority documentation updates / bug fixes

**Comment by tloubrieu-jpl** [comment]
This works since last week
