### ISSUE TITLE
Draft action: read the doi from the pds4 label

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#114]
When DOI is updated from a pds4 label the DOI can be found in the label.

In this case, it needs to be read and added to the OSTI XML label in the draft action.

**Applicable requirements**
:unicorn: #9
:unicorn: #5 
:unicorn: #11

**Comment by tloubrieu-jpl** [comment]
@jordanpadams do you have a PDS4 label example containing a DOI ? Where will it be (approximate xpath), if not we will be able to find it, don't worry about that. Thanks

**Comment by jordanpadams** [comment]
https://pds.nasa.gov/data/pds4/test-bundles/urn-nasa-pds-insight_documents/bundle_insight_documents.xml

`//Citation_Information/doi`

<img width="675" alt="Screen Shot 2020-11-02 at 9 59 00 AM" src="https://user-images.githubusercontent.com/33492486/97902161-09fa6400-1cf2-11eb-95c5-c4ff832a7099.png">

**Comment by tloubrieu-jpl** [comment]
@tloubrieu-jpl needs to update the MANIFEST.in file

**Comment by gxtchen** [comment]
@jordanpadams @tloubrieu-jpl Do I need to make any changes to the xml in order to test this.
I tried entering pds-doi-cmd draft -i urn-nasa-pds-insight_documents/bundle_insight_documents.xml -s gxchen@jpl.nasa.gov -n eng but it failed.

Thanks
Gary

**Comment by tloubrieu-jpl** [comment]
Hi Gary,

I ran it from the remote url input which should be the same as from the local file:
% pds-doi-cmd draft -i https://pds.nasa.gov/data/pds4/test-bundles/urn-nasa-pds-insight_documents/bundle_insight_documents.xml -s ***@***.*** -n eng

I got an error message (hopefully the same as yours) saying:
“pds_doi_service.core.input.exceptions.WarningDOIException: TitleDoesNotMatchProductTypeException : DOI with lidvid 'urn:nasa:pds:insight_documents::2.0' title 'Mars InSight Lander Document Archive' does not contains product specific type suffix 'bundle'. Product specific type suffix should be in the title.”

So you can either add bundle at the end of the title, or “force” the warning, which I did:
% pds-doi-cmd draft -i https://pds.nasa.gov/data/pds4/test-bundles/urn-nasa-pds-insight_documents/bundle_insight_documents.xml -s ***@***.*** -n eng -f

And that worked.

I will create a ticket to make silent of the debug log by default so that it is easier to see the log message (https://github.com/NASA-PDS/pds-doi-service/issues/206)

We should also add that the –force or -f option can be used to force a warning message (https://github.com/NASA-PDS/pds-doi-service/issues/207)

Let me know if you have other concerns about this ticket,

Thanks,

Thomas


From: Gary Chen ***@***.***>
Reply-To: NASA-PDS/pds-doi-service ***@***.***>
Date: Sunday, May 30, 2021 at 11:33 AM
To: NASA-PDS/pds-doi-service ***@***.***>
Cc: "Loubrieu, Thomas G (US 398F)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-PDS/pds-doi-service] Draft action: read the doi from the pds4 label (#114)


@jordanpadams<https://urldefense.us/v3/__https:/github.com/jordanpadams__;!!PvBDto6Hs4WbVuu7!YvSkf49lC15UzjorQJC4cdQGWJ5xcTe8wJ0-Y5irsp75kG4ydLC_UOlwA0jS4zvMYgEO2WrZa1A$> @tloubrieu-jpl<https://urldefense.us/v3/__https:/github.com/tloubrieu-jpl__;!!PvBDto6Hs4WbVuu7!YvSkf49lC15UzjorQJC4cdQGWJ5xcTe8wJ0-Y5irsp75kG4ydLC_UOlwA0jS4zvMYgEO23Ft3ME$> Do I need to make any changes to the xml in order to test this.
I tried entering pds-doi-cmd draft -i urn-nasa-pds-insight_documents/bundle_insight_documents.xml -s ***@***.******@***.***> -n eng but it failed.

Thanks
Gary
