### ISSUE TITLE
the sqllite database should be created at the same location, whereever the command are launched from

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#122]
**Describe the bug**
the location of the local database depends on where the command is launched from

**To Reproduce**
launch the same reserve of draft command from 2 different directories.
Not duplicate will be found since 2 different databases will be created.

**Expected behavior**
Always create the database where the package is deployed.

** Version of Software Used**
1.0.1

**Comment by jordanpadams** [comment]
@tloubrieu-jpl should this be configurable if it is not set? this way we can set it to some default directory on our servers i operations

**Comment by jordanpadams** [comment]
@tloubrieu-jpl  @rchenatjpl was this bug identified by I&T or some other reason?

**Comment by rchenatjpl** [comment]
I don't know this issue. I don't think it's a result of any I&T test.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams I found this bug while assisting @rchenatjpl on I&T.
The location of the database is already configurable but the default configuration is a relative path which is not right. I will work on that today.
