### ISSUE TITLE
do not require "Bundle" in the bundle.xml title

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/pds-doi-service#123]
Many (10%?) bundles have titles that do NOT end with "Bundle". Neither the PDS4 Standards nor the Data Provider Handbook requires this. Also, note that 1 warning and 1 error are extremely similar, "...Product specific type suffix should be in the title"
[doi5.bundleNone.xml.zip](https://github.com/NASA-PDS/pds-doi-service/files/5632295/doi5.bundleNone.xml.zip)

% pds-doi-cmd draft -n eng -i testDoi/doi5.bundleNone.xml -s"rchen@jpl.caltech.edu"
INFO pds_doi_core.cmd.pds_doi_cmd:main run_dir /Users/rchen/Desktop/test
INFO pds_doi_service.core.util.config_parser:get_config search configuration files in ['/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/conf.ini.default', '/Users/rchen/.virtualenvs/pds-doi-service/pds_doi_service.ini', '/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service.ini']
INFO pds_doi_service.core.util.config_parser:get_config used configuration following files ['/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/conf.ini.default', '/Users/rchen/.virtualenvs/pds-doi-service/pds_doi_service.ini']
INFO pds_doi_service.core.util.config_parser:get_config search configuration files in ['/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/conf.ini.default', '/Users/rchen/.virtualenvs/pds-doi-service/pds_doi_service.ini', '/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service.ini']
INFO pds_doi_service.core.util.config_parser:get_config used configuration following files ['/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/conf.ini.default', '/Users/rchen/.virtualenvs/pds-doi-service/pds_doi_service.ini']
INFO pds_doi_service.core.util.config_parser:get_config search configuration files in ['/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/conf.ini.default', '/Users/rchen/.virtualenvs/pds-doi-service/pds_doi_service.ini', '/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service.ini']
INFO pds_doi_service.core.util.config_parser:get_config used configuration following files ['/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/conf.ini.default', '/Users/rchen/.virtualenvs/pds-doi-service/pds_doi_service.ini']
INFO pds_doi_service.core.util.config_parser:get_config search configuration files in ['/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/conf.ini.default', '/Users/rchen/.virtualenvs/pds-doi-service/pds_doi_service.ini', '/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service.ini']
INFO pds_doi_service.core.util.config_parser:get_config used configuration following files ['/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/conf.ini.default', '/Users/rchen/.virtualenvs/pds-doi-service/pds_doi_service.ini']
INFO pds_doi_service.core.util.config_parser:get_config search configuration files in ['/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/conf.ini.default', '/Users/rchen/.virtualenvs/pds-doi-service/pds_doi_service.ini', '/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service.ini']
INFO pds_doi_service.core.util.config_parser:get_config used configuration following files ['/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/conf.ini.default', '/Users/rchen/.virtualenvs/pds-doi-service/pds_doi_service.ini']
INFO pds_doi_service.core.util.config_parser:get_config search configuration files in ['/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/conf.ini.default', '/Users/rchen/.virtualenvs/pds-doi-service/pds_doi_service.ini', '/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service.ini']
INFO pds_doi_service.core.util.config_parser:get_config used configuration following files ['/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/conf.ini.default', '/Users/rchen/.virtualenvs/pds-doi-service/pds_doi_service.ini']
INFO pds_doi_core.actions.actions:parse_arguments input = testDoi/doi5.bundleNone.xml
INFO pds_doi_core.actions.actions:parse_arguments node = eng
INFO pds_doi_core.actions.actions:parse_arguments submitter = rchen@jpl.caltech.edu
INFO pds_doi_core.actions.actions:parse_arguments force = False
INFO pds_doi_core.actions.actions:parse_arguments keyword = None
INFO pds_doi_core.actions.actions:_run_single_file input_file testDoi/doi5.bundleNone.xml
INFO pds_doi_core.util.doi_validator:validate_against_xsd xsd_filename,is_valid ('/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/iad_schema.xsd', True)
INFO pds_doi_core.util.doi_validator:_check_field_site_url doi.site_url https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Atest&version=1.0
INFO pds_doi_core.db_util.doi_database:select_latest_rows ready to execute request SELECT * from doi WHERE is_latest=1  AND lower(title) IN (:title_0)  ORDER BY update_date
INFO pds_doi_core.db_util.doi_database:select_latest_rows with parameters {'title_0': 'lunar crustal magnetic field map'}
INFO pds_doi_core.db_util.doi_database:create_connection sqlite3.version 2.6.0
Traceback (most recent call last):
  File "/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/actions/draft.py", line 167, in _run_single_file
    self._doi_validator.validate(doi_obj)
  File "/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/doi_validator.py", line 228, in validate
    self._check_field_title_content(doi)
  File "/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/util/doi_validator.py", line 128, in _check_field_title_content
    raise TitleDoesNotMatchProductTypeException(msg)
pds_doi_service.core.input.exceptions.TitleDoesNotMatchProductTypeException: DOI with lidvid 'urn:nasa:pds:test::1.0' title 'Lunar Crustal Magnetic Field Map'  does not contains product specific type suffix 'bundle'. Product specific type suffix should be in the title

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rchen/.virtualenvs/pds-doi-service/bin/pds-doi-cmd", line 10, in <module>
    sys.exit(main())
  File "/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/cmd/pds_doi_cmd.py", line 32, in main
    output = action.run()
  File "/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/actions/draft.py", line 208, in run
    doi_label = self._run_single_file(input_file, self._node, self._submitter, contributor_value, self._force, self._keyword)
  File "/Users/rchen/.virtualenvs/pds-doi-service/lib/python3.8/site-packages/pds_doi_service/core/actions/draft.py", line 174, in _run_single_file
    raise WarningDOIException(str(e))
pds_doi_service.core.input.exceptions.WarningDOIException: DOI with lidvid 'urn:nasa:pds:test::1.0' title 'Lunar Crustal Magnetic Field Map'  does not contains product specific type suffix 'bundle'. Product specific type suffix should be in the title

**Comment by rchenatjpl** [comment]
Identification_Area/product_class can tell you Product_Bundle, _Collection, _Document,...

**Comment by jordanpadams** [comment]
@tloubrieu-jpl this is probably a best practice and instead, if the title does not contain bundle/collection/document in the title, we should just append it at the end. thoughts?

**Comment by tloubrieu-jpl** [comment]
I noticed that the -f option disables the verification of this rule. @rchenatjpl @jordanpadams is that ok ?

I don't like very much idea of automatically updating the title since we are not sure if the produced result will be better than the initial title.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl OK by me

**Comment by jordanpadams** [comment]
@tloubrieu-jpl if we don't fix this, lets make sure we tag it with the appropriate "wontfix" label

**Comment by rchenatjpl** [comment]
-f sounds good to me - I didn't know about that option.
