### ISSUE TITLE
'pds-doi-cmd draft' chokes on a legit Product_Document

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/pds-doi-service#129]
How many possibilities do you want to cover? The attached is a valid Product_Document that 1) has no Citation_Information/author_list, and 2) does not have the string "documentation" in title. 'pds-doi-cmd draft' chokes on both those issues. The 2nd happens often.

[rimfax_bundle_sis.xml.zip](https://github.com/NASA-PDS/pds-doi-service/files/5641290/rimfax_bundle_sis.xml.zip)

**Comment by tloubrieu-jpl** [comment]
@rchenatjpl @jordanpadams 

Currently the author is mandatory in the schematron applied to the OSTI record. I did not check on OSTI side if it is actually required but I suspect it is (it was on dataCite).

For the title, the option -f or --force enable to skip the control on the title and other possible warnings. Could that work ? Or do you want to completely remove the control ?

**Comment by jordanpadams** [comment]
@rchenatjpl even if the PDS4 IM does not require this, an author_list will be required to get a DOI. I think that is a reasonable request. we should just make sure the error handling is clear about what this error is.

**Comment by tloubrieu-jpl** [comment]
I've added an explicit exception management for this case. Error message is now:
pds_doi_service.core.input.exceptions.CriticalDOIException: missing author in pds4 input, please complete it
