### ISSUE TITLE
API POST /dois should accept DOI OSTI format in payload

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#148]
We need a way for a user to save an updated draft version of an OSTI DOI record.

We can extend the /dois POST function to accept the OSTI DOI format when action=draft

To implement that we will have some kind of identity function for the core component, the draft action should accept the OSTI format and the response will be the OSTI format. The only things done by the function will be:
- validate the osti doi format
- save the updated format in the transaction database.

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl feel free to adapt the initial design proposal to whatever you thing works best.

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl will create a class to handle any input/output (files, urls).

**Comment by tloubrieu-jpl** [comment]
As part of this ticket the draft exception management will be corrected.

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl is making progress on that (testing phase now).

A new step would be to check how non supported format are handled for one specific action. Requirements on that needs to be detailed.

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl wil you be able to do a pull request for this ticket tomorrow ? @eddiesarevalo will need that to progress further on the UI side. Thanks.

**Comment by collinss-jpl** [comment]
@tloubrieu-jpl Sorry for delay, will make getting the PR up top priority

**Comment by collinss-jpl** [comment]
@tloubrieu-jpl PR is now up https://github.com/NASA-PDS/pds-doi-service/pull/151
