### ISSUE TITLE
As an operator, I want to reserve a DOI through DataCite

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#171]
For more information on how to populate this new feature request, see the PDS Wiki on User Story Development:

https://github.com/NASA-PDS/nasa-pds.github.io/wiki/Issue-Tracking#user-story-development

## Motivation
...so that I can reserve a DOI

## Additional Details
<Please prove any additional details or information that could help provide some context for the user story.>

## Acceptance Criteria
**Given** Spreadsheet containing a simple subset of information (already defined)
**When I perform** A reserve request
**Then I expect** To reserve a DOI through DataCite

## Applicable Requirements
🦄 #13 
🦄 #6

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl worked on the json template for dataCite.

the new templating library that Scott uses is jinja

**Comment by tloubrieu-jpl** [comment]
So that @jordanpadams and ron can review the new DOIs on dataCite, @collinss-jpl will send one of the test DOI to them.

**Comment by tloubrieu-jpl** [comment]
That would be good to connect the command line option for the target DOI infra to be able to test dataCite DOIs.
