### ISSUE TITLE
As an operator, I want to update DOI metadata through DataCite

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#175]
For more information on how to populate this new feature request, see the PDS Wiki on User Story Development:

https://github.com/NASA-PDS/nasa-pds.github.io/wiki/Issue-Tracking#user-story-development

## Motivation
...so that I can update the metadata associated with a reserved (aka `draft) or released (aka `findable`) DOI.

## Additional Details
Per the info from Ron, can only update a DOI in a `draft` or `registered` state.
```
if the DOI is `findable`:
    `hide` DOI to move the DOI from `findable` to `registered` states

update DOI
```

## Acceptance Criteria
**Given** a DOI in `draft` state
**When I perform** an update of the DOI metadata, and a follow-on query to verify the results
**Then I expect** to see the DOI metadata has been updated

**Given** a DOI in `registered` state
**When I perform** an update of the DOI metadata, and a follow-on query to verify the results
**Then I expect** to see the DOI metadata has been updated

**Given** a DOI in `findable` state
**When I perform** an update of the DOI metadata, and a follow-on query to verify the results
**Then I expect** to see the DOI metadata has been updated

**Given** a DOI that does not exist
**When I perform** an attempted update of that DOI metadata
**Then I expect** to receive an error message that DOI does not exist

**Comment by tloubrieu-jpl** [comment]
PDS DOI will not use the dataCite `registered` status.

**Comment by tloubrieu-jpl** [comment]
Last acceptance criteria will be delayed and processed in a different ticket
