### ISSUE TITLE
As an API user I want to filter on lidvids with wildcards

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#177]
See ticket https://github.com/NASA-PDS/pds-doi-ui/issues/25 which will use this feature.

**Comment by jordanpadams** [comment]
@collinss-jpl not sure if you will be able to squeeze this in this sprint or not, but we can talk more about it tomorrow at the breakout if needed.

**Comment by collinss-jpl** [comment]
I have an initial implementation of the feature complete. Still need to tidy up the new code and add test cases. Will hopefully have a PR up by end of today.
