### ISSUE TITLE
As an API user, I want to always have an update date for the DOIs

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#184]
## Motivation
Currently when a DOI has been created but never updated, the update date is not available. In this case we want to have the update date equal to the creation date.

## Acceptance Criteria
**Given** a newly created DOI (e.g. reserved)
**When I perform** get /dois/<lidvid>
**Then I expect** to see a valid update date, the update date should be equal to the creation date in this case.

## Engineering Details

I think this should be implemented from the creation of the doi  when the transaction is recorded in the database.

**Comment by tloubrieu-jpl** [comment]
@c-suh @collinss-jpl is it still an issue, I am not seeing a problem with update dates in the latest development of Catherine ?

![image](https://user-images.githubusercontent.com/60993872/115777202-d677c880-a369-11eb-896c-c601e52f14a3.png)

**Comment by c-suh** [comment]
@tloubrieu-jpl I don't know if this satisfies the ticket? Searching by doi or lid as a query parameter will give `update_date`[1][2]. Searching as a path variable will give the `creation_date` (no update_date) and XML record[3]

[1] http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois?doi=10.17189%2F29466
[2] http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois?lid=urn:nasa:pds:lab_shocked_feldspars::2.0
[3] http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois/urn:nasa:pds:lab_shocked_feldspars::2.0

**Comment by collinss-jpl** [comment]
@tloubrieu-jpl This issue is still open from my perspective. I've found a number of issues with how creation/update times are being handled by the DOI service and I'm testing out fixes currently. Unfortunately I don't think I'll have the branch ready for review before we close out this sprint, but its close to being complete.

**Comment by tloubrieu-jpl** [comment]
@c-suh , @collinss-jpl Ok, sounds good, thanks.

So maybe the request 3 should also return the update_date.

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl found a consistent way to manage the update date. He is now testing that. That should be ready for review today.
