### ISSUE TITLE
As a SA, I want the operational deployment of the service to be secure

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#187]
## Motivation
...so that I accept to deploy it and feel comfortable with not risking to introduce a breach in our systems.

## Additional Details
We need to check how the service will be deployed and useable by the UI and discuss it with SAs so that the solution is acceptable for them.

## Acceptance Criteria
A plan accepted by SA's for the deployment of the API and acceptable by users for the accessibility of the UI.

## Engineering Details
- [ ] work with SAs to come up with a deployment strategy
- [ ] document secure deployment
- [ ] deploy on PDS I&T machine for testing

**Comment by tloubrieu-jpl** [comment]
See ticket https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-433

**Comment by jordanpadams** [comment]
Per breakout today:
- [ ] @tloubrieu-jpl - SAs will setup basic auth through Apache Server for accessing UI
- [ ] @collinss-jpl - update DOI Service to read and access basic auth

**Comment by tloubrieu-jpl** [comment]
I created a ticket for the basic authentication configuration https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-466

**Comment by tloubrieu-jpl** [comment]
The deployment documentation is on: https://osr.jpl.nasa.gov/wiki/pages/viewpage.action?pageId=152502275

**Comment by gxtchen** [comment]
@tloubrieu-jpl Can you create a user account for me to log in to https://pds-gamma.jpl.nasa.gov/dois/

**Comment by tloubrieu-jpl** [comment]
Hi @gxtchen , I sent you the credential on lft jpl service. You should have received a regular email informing you.
