### ISSUE TITLE
API accepts Reserve submissions with invalid LIDVIDs

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/pds-doi-service#191]
## 🐛 Describe the bug
An item to Reserve can be submitted successfully with invalid LIDVIDs, e.g. `urn`, `%$`,  `.` (a period), `urn:nasa:pds:<product>:<collection>:<bundle>` (without `::<version>`)

## 📜 To Reproduce
1. Fill in [Excel template](https://pds-engineering.jpl.nasa.gov/sites/default/files/DOI_reserve_template.xlsx) with reserve information
2. Connect to the API with `ssh -L 8085:localhost:8080 pds-dev3`, start local instance of DOI UI with `npm start` from root folder of https://github.com/NASA-PDS/pds-doi-ui/tree/search-metadata (currently not merged into master branch), and go to `localhost:3000` in your browser
3. Click on 'Reserve' in the top right
4. Upload file from step 1, fill in or select values for Submitter Email and Node, and click 'Reserve' button at bottom
5. If submission is successful (message with green background), click header 'DOI Reserve And Release' to see table of all items; your submitted item should be on top. OR go to http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois for full list and use Cmd/Ctrl + F to find your entry.

## 🕵️ Expected behavior
In the Excel sheet, the relevant field is column G (related resource LIDVID).
- If this is left blank, an error is shown on submission (personal opinion, the error message is not helpful to users: `Error: CriticalDOIException. Description: argument of type 'float' is not iterable`)
- Otherwise, if no other fields cause errors, the submission is accepted.

## 📚 Version of Software Used
N/A

## 🩺 Test Data / Additional context
- an attempted submission using an existing title will throw an error (unless it's same title AND same lidvid, then it's accepted, like the highlights in the screenshot below)
- use http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois or refer to the table on the DOI UI landing page to see existing records

##  🏞Screenshots
<img width="857" alt="Screen Shot 2021-04-27 at 6 08 46 PM" src="https://user-images.githubusercontent.com/18314609/116331051-c6a21f00-a783-11eb-8390-cf2278c986f2.png">

## 🖥 System Info
 - OS: irrelevant
 - Browser:  irrelevant
 - Version:  irrelevant
---

** :unicorn: Applicable requirements**

**Comment by c-suh** [comment]
@tloubrieu-jpl is this enough information? I changed it slightly when I realized that it accepts any value for a LIDVID, not just LIDs without a VID

**Comment by tloubrieu-jpl** [comment]
@collinss-jpl is adding rules to validate the lidvid provided.
