### ISSUE TITLE
As a user, I want the application to support the history of PDS's DOIs, especially the one created for PDS3 products

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#192]
## Motivation
...so that the application works for production.

## Additional Details

To initialize the transaction database with the history of DOI, run:

./pds_doi_service/core/util/initialize_production_deployment.py -i https://www.osti.gov/iad2/api/records -s loubrieu@jpl.nasa.gov -d venv/doi.db

Request to these DOIs do not work: 

- http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois/LRO-L-MRFLRO-2%2F3%2F5-BISTATIC-V3.0 
- http://localhost:8085/PDS_APIs/pds_doi_api/0.1/dois/LRO-L-MRFLRO-4-CDR-V1.0 return error 500

## Acceptance Criteria
**Given** the DOI service database containing all exist PDS DOIs
**When I perform** a query for a DOI with PDS3 Data Set ID as an identifier
**Then I expect** the DOI record to be returned from the database

**Comment by jordanpadams** [comment]
@tloubrieu-jpl just as a heads up, this issue is very tightly coupled with https://github.com/NASA-PDS/pds-doi-service/issues/180
