### ISSUE TITLE
As a user, I want to use the API with ids containing a slash (/)

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#198]
## Motivation
...so that I can work with PDS3 ids without replacing the '/' with a different character. 

## Additional Details

~The API need to be redesigned or extended so that the lid parameter can be passed as a request parameters (e.g. ?lid=...) insted of a query parameter e.g. .../dois/{lid}/submit~

- ~redesign the API~
- ~develop the new lid management~
- ~update the OSTI migration script to keep PDS3 ids as-is, with /.~  

## Acceptance Criteria
**Given** a PDS3 dataset with an Id containing a /
**When I perform** get DOI description
**Then I expect** to get the result

**Given** a PDS3 dataset with an Id containing a /
**When I perform** update the DOI description
**Then I expect** the result is updated

**Given** a PDS3 dataset with an Id containing a /
**When I perform** release the DOI
**Then I expect** the updated DOI is released

## Engineering Details

Per breakout design discussion:
- [ ] pds-doi-ui client will encode all `/` characters as `*` and pass to DOI service

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @collinss-jpl apologies i didn't realize the amount of effort this was going to take. if this has implications beyond just querying a DOI, but if it will not allow us to update DOI metadata, then I recommend we just encode PDS3 DOIs some other way from the client side.

**Comment by jordanpadams** [comment]
it's my understanding the status query will work as-is, but it sounds like the update part will not.

**Comment by jordanpadams** [comment]
per convo at 2021-05-20 breakout, UI will encode the '/' as '_'

**Comment by tloubrieu-jpl** [comment]
See https://github.com/NASA-PDS/pds-doi-service/issues/192
