### ISSUE TITLE
When installing the pds-doi-service from scratch I had an error with Flask version compatibility

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#199]
## 🐛 Describe the bug

When running 

pip install -r requirements.txt 

on a new virtual environment there is an error with the Falsk version compatibility

## 📜 To Reproduce
1. git clone ....
2. python -m venv venv
3. pip install -r requirements.txt

## 🕵️ Expected behavior

The pip install command should run without errors.

I think that works if I add an explicit version reference for Flask in the requirements.txt:

Flask==1.1.2

## 📚 Version of Software Used

Latest dev version on master

## 🖥 System Info

---

** :unicorn: Applicable requirements**

**Comment by tloubrieu-jpl** [comment]
This error is impacting I&T (blocking it).

**Comment by jordanpadams** [comment]
@tloubrieu-jpl do we also to merge the doc changes from Eddie for Gary to test as part of this?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams yes good idea. Although the document changes are not as critical for Gary just today.

**Comment by tloubrieu-jpl** [comment]
The new dependency has been added on master branch with commit https://github.com/NASA-PDS/pds-doi-service/commit/c70e01b1cc8d7c6f1c872f11ca33ed2258e16187#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552
