### ISSUE TITLE
Reserve a DOI capability

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#21]
**Applicable requirements**
:unicorn: #6
:unicorn: #11
:unicorn: #12

**Comment by tloubrieu-jpl** [comment]
The reserve DOI xls spreadsheet will contain a column with the originating discipline node coded with these values:
https://pds.jpl.nasa.gov/datastandards/documents/dd/current/PDS4_PDS_DD_1D00.html#d5e72146

The case of the inputs, in the xls spreadsheet must be ignored by the software (by converting everything to lower case).
