### ISSUE TITLE
Remove test and other transaction log data from public pypi distro

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#214]
## 📜 To Reproduce
1. Download tarball from `https://pypi.org/simple/pds-doi-service/`
2. Within the back there are some test remnants in the downloaded tarball:
 
<img width="1095" alt="Screen Shot 2021-06-22 at 11 14 42 AM" src="https://user-images.githubusercontent.com/33492486/122978166-0c760080-d34b-11eb-8d2a-ad6940b935f8.png">

## 🕵️ Expected behavior

These test resources should not be included in the distro.

## 📚 Version of Software Used

v1.1.1

## 🖥 System Info

---

## :unicorn: Applicable requirements
🦄 #212

**Comment by collinss-jpl** [comment]
New v2.0.0 build pushed to PyPI at https://pypi.org/project/pds-doi-service/2.0.0/

This version does not include the aforementioned test artifacts.
