### ISSUE TITLE
Document how to Deactivate a DOI (with curl command)

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#23]
**Applicable requirements**
:unicorn: #8

**Comment by jordanpadams** [comment]
Build 11.0 Descope Rationale: The deactivate function is used on very a limited basis and we have a manual workaround in the even that it is needed.

**Comment by tloubrieu-jpl** [comment]
Beware the transaction database will not be updated. Would be better to code the deactivate command.

**Comment by jordanpadams** [comment]
closing. will implement against requirement
