### ISSUE TITLE
As an operator, I want to sync our local database with DataCite metadata

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#239]
## 💪 Motivation
...so that I can 

## 📖 Additional Details

This should have a configurable DOI prefix so we can sync 1 or more DOI prefixes into the database.

Potential use cases:
* Run once for PDS EN DOIs to update database after database failure / first start-up
* Cron to continuously update DOI database with SBN DOIs minted elsewhere

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by collinss-jpl** [comment]
@jordanpadams Question about this use case: "Cron to continuously update DOI database with SBN DOIs minted elsewhere"

Where exactly is "elsewhere" here? Somewhere other than OSTI or DataCite? I.E. will this script need to handle credentials and a URL endpoint other than those we configure in the DOI service config?

**Comment by jordanpadams** [comment]
@collinss-jpl they are registered with DataCite, just with a different identifier. Hopefully you can just query that info (but will not be able to update). Here are their DOI prefixes: SBN/PSI: 10.260332, SBN/UMD: 10.26007
