### ISSUE TITLE
Update Released DOI capability

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#24]
**Applicable requirements**
:unicorn: #9

**Comment by tloubrieu-jpl** [comment]
This will be done by implemented the draft/release function with a OSTI DOI label as input.

**Comment by tloubrieu-jpl** [comment]
To me the core idea of the release action is to use the XML as it is produced by reserve or draft and be able to submit it to OSTI. This is already developed although not as an action yet which can be called in command line and this needs to register a transaction on its own (ticket #46 is about that).

The update released DOI action will take as input one of these XML that the user will be able to update before re-releasing it. So you will need to consider the OSTI format as an input. This is the basic implementation we can start with for ticket #26.
 
But as I think we mentioned in the morning we can also update from different formats (pds4 label, xsl spreadsheet). I am not sure if this should be an action standing by itself. That might be a flag –update-or-create that applies to reserve/draft/release actions. This would make the software tore-use the same doi record if the doi or lidvid is already in the database.

**Comment by tloubrieu-jpl** [comment]
It is unclear what should be posted to OSTI for the release action.

We will discuss that specifically at 3:30 today.
