### ISSUE TITLE
Fix test failure with flask_testing module

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#247]
## 🐛 Describe the bug

See https://github.com/NASA-PDS/pds-doi-service/runs/3664070311?check_suite_focus=true#step:6:121

**Comment by nutjob4life** [comment]
Not a problem in the PDS DOI Service, but an exposure of a [problem with the Roundup Action](https://github.com/NASA-PDS/roundup-action/issues/64).

**Comment by jordanpadams** [comment]
Should be closed per https://github.com/NASA-PDS/roundup-action/pull/65 and https://github.com/NASA-PDS/github-actions-base/pull/21
