### ISSUE TITLE
As a PDS Operator, I want to perform a bulk update of a specific field across many DOI records

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#257]
## 💪 Motivation
...so that I can update metadata in DataCite for specific fields that have changed across the PDS. For instance, for https://github.com/NASA-PDS/pds-doi-service/issues/226, we will want to update all records with licensing info.

## 📖 Additional Details

Two use cases to consider here:
1. Bulk update of all PDS DOI records (high priority)
2. Bulk update of subset of PDS DOI records by node (lower priority depending on how difficult it would be to implement)

## ⚖️ Acceptance Criteria
**Given** a proposed update to DOI metadata for all PDS DOI records, e.g. change all license information to `X`, in a CSV
**When I perform** execution of this new tool like `pds-doi-update --config key_value.csv`
**Then I expect** all PDS records will update with this new metadata value(s)

## ⚙️ Engineering Details

Per discussion today, @collinss-jpl to develop a Jupyter notebook(s) to make these updates and document how an operator could spin up a notebook and tweak for whatever bulk update they need

**Comment by tloubrieu-jpl** [comment]
The product of this ticket should be a jupyter-notebook.

**Comment by tloubrieu-jpl** [comment]
For bulk updates the node argument is not appropriate and will be made optional.

But the validation will check that the node is available in the labels.

**Comment by tloubrieu-jpl** [comment]
The notebook proposed is there  https://github.com/NASA-PDS/doi-service/blob/main/src/pds_doi_service/notebooks/Bulk%20Record%20Update.ipynb
