### ISSUE TITLE
Develop DOI Status / Query component

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#27]
## Design Details
See https://github.com/NASA-PDS/pds-doi-service/blob/master/docs/design/pds-doi-service-srd.md#listretrieve-a-doi

## Inputs
This component should enable the status query of:
* DOI (`1..*`) - should return `0..1` DOI summary objects
* LID (`1..*`) - should return `0..*` DOI summary objects
* LIDVID (`1..*`) - should return `0..1` DOI summary objects
* Submitter (`1..*`) - should return `0..*` DOI summary objects
* Discipline Node Abbreviation (`1..*`) - should return `0..*` DOI summary objects
* Submission datetime range (`start`, `end`) (ISO-8601 format) - should return `0..*` DOI summary objects

## Outputs
Based upon the DOI summary objects returned from the database, the software should return the summaries in two possible formats (specified via the API):
* JSON
* CSV

**Applicable requirements**
:unicorn: #30

**Comment by tloubrieu-jpl** [comment]
Possible combinations of criteria are:
- DOI
- LID
- LIDVID
- submitter + optional time period
- node id + optional time period
- time period
- None

They all apply to record with is_latest criteria being True.

**Comment by tloubrieu-jpl** [comment]
The command line arguments can be:
--doi, single entry doi1, or list doi1,doi2
--lidvid, single entry or list
--lid, single entry of list
--submitter, email, single entry or list
--node, short name (e.g. img), single entry or list
--start-time, iso8601 format
--end-time , iso8601 format
