### ISSUE TITLE
As a user, I want to update the LIDVID associated with a DOI 

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#278]
## 💪 Motivation
...so that I can answer the request of Discipline Node who sometime update the lidvid 

## 📖 Additional Details

1) We want to provide Ron with a command to change the lidvid and the default landing page URL associated to a specific DOI
2) In the UI/backend API when a user tries to release a DOI which has already been reserved with a different lidvid, he/she will get a specific message proposing to contact pdsen-operator to switch the lidvid.

Note: This should be possible on both the reserve or release steps

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by tloubrieu-jpl** [comment]
@jordanpadams will create a different ticket so to be able to add new versions of lid for a given DOI.

**Comment by gxtchen** [comment]
@tloubrieu-jpl what parameters does update take?
help doesn't and documents should be update as well.
 positional arguments:
  {reserve,update,release,check,list}

This is too simple.

**Comment by jordanpadams** [comment]
@collinss-jpl ☝️

**Comment by tloubrieu-jpl** [comment]
Hi @gxtchen ,

The help work also if you do:

`pds-doi-cmd update --help`

That will give you specific details on the subcommand `update`.

But the doc at https://nasa-pds.github.io/doi-service/usage/index.html need to be updated as you said.

@collinss-jpl when you update the doc can you make sure it is clear that the option --help also applies to subcommand. One example can help maybe. Thanks
