### ISSUE TITLE
Develop ability to maintain a transaction log database

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#29]
See https://github.com/NASA-PDS/pds-doi-service/blob/master/docs/design/pds-doi-service-srd.md#listretrieve-a-doi for details

**Comment by tloubrieu-jpl** [comment]
We need a dictionary to match steward ids (e.g. img) with the long name node (e.g Cartography and Imaging Sciences Discipline).

The argument of the command line with be steward id. 
The directory name of the transaction archive with also be the steward id.
The value in the DOI record is the long name as for now.
