### ISSUE TITLE
Develop maintain internal database of DOI requests

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#31]
Purpose of this task is to develop an internal database for maintaining the data in the DOI Summary object.

See https://github.com/NASA-PDS/pds-doi-service/blob/master/docs/design/pds-doi-service-srd.md#listretrieve-a-doi for the data we want to maintain in the database

**Comment by tloubrieu-jpl** [comment]
For reserve action it is not appropriate to have the email in the command line argument. That should be in the xls spreadsheet or csv.
