### ISSUE TITLE
Develop Pending DOI Handler component for iteratively querying OSTI for DOI status until status change

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#33]
## START
Once a DOI submission enters a `pending` state, this handler component is triggered to will iteratively query OSTI for the current status of the pending DOI submission(s). Note: All submissions should enter this state when submitted to OSTI, unless there is an immediate failure returned.

## Inputs
* List of `pending_submissions` - this dictionary contains all the submitted objects
    * the identifiers for these objects may be:
        * DOI(s) - already reserved/released a some prior point
        * LIDVID(s) - first time attempting to reserve/release a DOI for this product

## Capabilities
Once a status change has been identified for individual members of `pending_submissions`:
* update the database with the updated status
* return to iterating over the remaining `pending_submissions` (Note: be sure to maintain those submissions whose status has updated so we can report on them once all `pending_submissions` have been updated.)

Once all members of `pending_submissions` have changed status (or a timeout has occurred):
* send email notification to the Submitter and pdsen-doi-test@jpl.nasa.gov / pdsen-doi@jpl.nasa.gov with list of `submitted_dois` DOI summary metadata
* trigger [Discipline Node report generation](#34) per the discipline node of the Submitter

**Comment by tloubrieu-jpl** [comment]
The triggering part or scheduling of the calls will be done later in separate ticket or implementation (e.g. crontab or integration to API server)

**Comment by tloubrieu-jpl** [comment]
Qui had a temporary issues with certificate. It solved itself.

**Comment by jordanpadams** [comment]
@qchaupds status: updating code based upon @tloubrieu-jpl 's PR comments
