### ISSUE TITLE
Develop simple regression test suite for deployment

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#41]
Received some inputs from Ron regarding some example inputs/outputs.

**Comment by tloubrieu-jpl** [comment]
Implement the verification that the new software reserve and draft steps work as for the historical processing sent by Ron.

Use behave for integration tests:
 Launch the tests:
$behave

Define the tests:
features/*.feature

Implement the tests in:
features/steps/steps.py

**Comment by jordanpadams** [comment]
@qchaupds status: completed an initial regression test for the `reserve` and will start working on the `draft` function.
