### ISSUE TITLE
Update documentation for operational installation and usage

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#42]
- [ ] Develop Sphinx documentation for the repo
- [ ] Documentation should include the following sections:
    - [ ] Installation
    - [ ] Usage
        - [ ] How to reserve a DOI
        - [ ] How to release a DOI (draft then release)
        - [ ] How to update DOI metadata (query then release)
    - [ ] Development
    - [ ] Support

See https://github.com/NASA-PDS/pds-deep-archive and https://nasa-pds.github.io/pds-deep-archive/# for an example of the docs. See docs directory for how the structure the RST files: https://github.com/NASA-PDS/pds-deep-archive/tree/master/docs

**Comment by tloubrieu-jpl** [comment]
First version available on https://nasa-pds.github.io/pds-doi-service/index.html

Need to be proof readed and add configuration documentation
