### ISSUE TITLE
API Implementation for DOI Service

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/pds-doi-service#52]
**Applicable requirements**
:unicorn: #35
:unicorn: #30
:unicorn: #5
:unicorn: #9
:unicorn: #7
:unicorn: #6

**Comment by tloubrieu-jpl** [comment]
From initial design of the API the end-point to implement are:
![image](https://user-images.githubusercontent.com/60993872/96191860-cf26bc80-0ef9-11eb-88bb-ba501d21ac18.png)

**Comment by jordanpadams** [comment]
October Schedule Status ⏳:  On track

**Comment by jordanpadams** [comment]
📆  November Schedule Status: Delayed 1 sprint due to new DOI User Interface developments.
