### ISSUE TITLE
validate the submitted OSTI record against a schema

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#56]
Plug the OSTI schema updated by Ron in the code at the DOI validation step.

See comments for schema to use.

**Comment by tloubrieu-jpl** [comment]
Add a private method to the schematron_validator (osti_validator): _validate_schema().

Add a call to this method in the public validate() method.

**Comment by tloubrieu-jpl** [comment]
[iad_1.0.0_edited_20200818b.xsd.zip](https://github.com/NASA-PDS/pds-doi-service/files/5091799/iad_1.0.0_edited_20200818b.xsd.zip)

**Comment by jordanpadams** [comment]
New XSD and schema:
[iad_1.0.0_20200819.zip](https://github.com/NASA-PDS/pds-doi-service/files/5098687/iad_1.0.0_20200819.zip)

**Comment by tloubrieu-jpl** [comment]
Comments on the schema:
- as we use the schema to validate  records submitted to OSTI, id and doi should be optional
- we don't send date_record_added, date_record_updated to OSTI either. Should we ? They are mandatory in the XSD
- authors/contributors:
   - the order of tags does not feel intuitive (last_name is first). Is there a reason for that ?
   - middle_name is mandatory should that be so ? We can set it empty but I would prefer not to send it if there is none. In the PDS4 example we used we did not find a middle_name,  only first_name initial and last_name (see https://pds-imaging.jpl.nasa.gov/data/nsyt/insight_cameras/bundle.xml).
- contact_name, contact_org, contact_email, contact_phone where in our initial test case, it is not in the XSD, is it missing there or should we remove them from our output ?
- product_nos is not in the XSD but I think we added that a some point in the development process.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl 
> Comments on the schema:
> 
> * as we use the schema to validate  records submitted to OSTI, id and doi should be optional
> * we don't send date_record_added, date_record_updated to OSTI either. Should we ? They are mandatory in the XSD



> * authors/contributors:
>   
>   * the order of tags does not feel intuitive (last_name is first). Is there a reason for that ?
>   * middle_name is mandatory should that be so ? We can set it empty but I would prefer not to send it if there is none. In the PDS4 example we used we did not find a middle_name,  only first_name initial and last_name (see https://pds-imaging.jpl.nasa.gov/data/nsyt/insight_cameras/bundle.xml).
> * contact_name, contact_org, contact_email, contact_phone where in our initial test case, it is not in the XSD, is it missing there or should we remove them from our output ?
> * product_nos is not in the XSD but I think we added that a some point in the development process.

**Comment by tloubrieu-jpl** [comment]
After feedback from @Ron and @jordanpadams Jordan, decision to resolve discrepancies between current DOI output and schema are:
- in output, if 'id' and 'doi' and not defined yet, empty tags are provided (@qchaupds )
- date_record_added and date_record_updated are be added to the output (@qchaupds ) 
- authors/contributors:
  - in XSD, sequence should be first_name, middle_name, last_name (@Ron)
  - in software, the middle_name tag is always generated. It is empty when no value is known (@qchaupds )
- contact_name, contact_org, contact_email, contact_phone are added to the xsd schema (@Ron)
- product_nos is removed from the software output (@qchaupds ).

@qchaupds, you should implement the necessary code updates for empty tag management in the object which read and write doi object from osti record format. This might also have an impact on the verification rule, hopefully not.
