### ISSUE TITLE
Mock web UI for DOI management 

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#67]
Propose web UI mock up for users (e.g. from discipline node) to assign DOI.

The workflow for assigning is https://github.com/NASA-PDS/pds-doi-service/blob/master/docs/design/pds-doi-service-workflow.png

The functions the user can perform with the software are described in the command line manual https://nasa-pds.github.io/pds-doi-service/usage/index.html

**Comment by jordanpadams** [comment]
![doi_service_ui_workflow](https://user-images.githubusercontent.com/33492486/93536799-b88f4480-f8fe-11ea-9588-af35c95faa8a.png)

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo works with the new design system

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo should we move this ticket to next sprint ? Thanks

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl Yes lets move it to the next sprint as this one is already over.

**Comment by jordanpadams** [comment]
@eddiesarevalo has made progress on some of the mock-ups. next steps on release and reserve.

manual process for now: https://pds-engineering.jpl.nasa.gov/content/doi

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo does not have access to the web site. He needs a login.

In the mean time, the most important part is:
Reserve a DOI:

Complete the spreadsheet spreadsheet template, one line per requested DOI
Email the spreadsheet  to pds-operator@jpl.nasa.gov with subject "Reserve DOI: "

DOI initial release:

      Email the PDS4 label to pds-operator@jpl.nasa.gov with subject "Release DOI"

DOI update, 2 options

     a. Send the updated PDS4 label to pds-operator@jpl.nasa.gov with subject "Update DOI". Provide the DOI in your email.

     b. Send the updated OSTI DOI label to pds-operator@jpl.nasa.gov with subject "Update DOI" (the OSTI label must contain the DOI).

**Comment by tloubrieu-jpl** [comment]
For reserve we consider that some user will create a spreadsheet from their local database and some other will edit the inputs manually.

As a consequence, for reserve UI we want:
1) the user can upload a spreadsheet format (can be simple CSV)
2) the user can visualize the content of the CSV and edit it 
3) the user can post the content of the spreadsheet to the API

The API will parse the payload and use the function developed for the command line access.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo  still need to mock the forms (wireframe, very simple). 
Specific tickets have been created for the development.

**Comment by eddiesarevalo** [comment]
Quick set of mock ups generally outlining how the app will look: [https://app.zenhub.com/files/236099103/ef9e5e30-eadb-4a06-b926-07ba8ef3fa6e/download](https://app.zenhub.com/files/236099103/ef9e5e30-eadb-4a06-b926-07ba8ef3fa6e/download)

**Comment by tloubrieu-jpl** [comment]
[doi-ui-mock-commented.pdf](https://github.com/NASA-PDS/pds-doi-service/files/5468199/doi-ui-mock-commented.pdf)

@eddiesarevalo thanks for this first iteration. I've added my comments. May be we can discuss them during a meeting. I will organize that beginning of the next week. Thanks again.

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl I tried reading your comments but for some reason I am unable to access them. Can you please try sending them again?
![Screen Shot 2020-11-02 at 5.29.07 PM.png](https://images.zenhubusercontent.com/5e98a8928301b57ff5d93d52/41461b88-6dbc-42f4-9f9f-c67880b14e8c)

I changed the review pages that what we discussed during our meeting. Here is the latest version:
[https://app.zenhub.com/files/236099103/103c18ad-db31-4678-a5e2-02be61a5b6a2/download](https://app.zenhub.com/files/236099103/103c18ad-db31-4678-a5e2-02be61a5b6a2/download)

**Comment by tloubrieu-jpl** [comment]
[doi-ui-mock (1).pdf](https://github.com/NASA-PDS/pds-doi-service/files/5481583/doi-ui-mock.1.pdf)

**Comment by tloubrieu-jpl** [comment]
Thanks @eddiesarevalo for your new iteration. This works.
However I think, we still need a case in first release screen where the user will create a DOI from a PDS4 Label URL. The inputs with doi or lidvid are for DOI update. Can you include that creation case ? Thanks

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl Thanks for your suggestions! I was able to see the comments and made the changes that could still be made from your comments. I also add the difference between the doi update and new release. 

[https://app.zenhub.com/files/236099103/4bbfa627-050a-4a28-9f3c-4a1cbb467c33/download](https://app.zenhub.com/files/236099103/4bbfa627-050a-4a28-9f3c-4a1cbb467c33/download)

**Comment by tloubrieu-jpl** [comment]
Thanks Eddie. That works. One little thing, screen 6 (your doi is being submitted) is going to be the one just before the last screen, instead of where it is now.

When you develop ideally you would need to connect to the API to adjust  the sequence of screens if needed.

**Comment by eddiesarevalo** [comment]
@tloubrieu-jpl I made that last change. Here is the current version:
[https://app.zenhub.com/files/236099103/45800653-a8bb-44f6-a6f4-bd153fd4f7a3/download](https://app.zenhub.com/files/236099103/45800653-a8bb-44f6-a6f4-bd153fd4f7a3/download)

**Comment by tloubrieu-jpl** [comment]
Thanks @eddiesarevalo . That works for now. We will need some adjustment when you will develop. For example we would not need the doi input for the screen that I asked you to move, and this screen will be optional. sometimes the release will be completed imediatly and the user will get to the last screen.
