### ISSUE TITLE
initialize production deployment with pre-existing dois

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#71]

**Comment by qchaupds** [comment]
Do we have an example input for the Python code to parse from?

Currently have a one-off script to parse an input from the 'reserve' action as an exercise and code to write to database but it is unlikely the true format of the input for this ticket.

**Comment by qchaupds** [comment]
After chatting with everyone, the recommendation is to query OSTI (test and operation) for current DOI, parse the output and insert every record into database.  More details coming as implementation goes.

**Comment by tloubrieu-jpl** [comment]
To initiate node use data curator convert if necessary, otherwise use ENG.

For submitter, let it empty or if mandatory could use (pds-operator@...).

**Comment by qchaupds** [comment]
As of Tuesday afternoon of 09/29/2020 the test and operational servers at DOI has the following count of DOIs:

https://www.osti.gov/iad2test/api/records 198 DOIs
https://www.osti.gov/iad2/api/records 602 DOIs

The one-off script is able to query both servers and parse the output for metadata required for writing to local database.
Doing this allow us to flush out issues with the parsing of content coming out from the server(s) as the content varies depends on who is doing the submission.

**Comment by qchaupds** [comment]
As of this morning 09/30/2020 at 11:05 AM, the number of DOIs on test server is actually
6789

**Comment by tloubrieu-jpl** [comment]
@qchaupds can you do a pull request for that today or early tomorrow ? Otherwise we can move this issue to next sprint, that is not a problem. Thanks

**Comment by tloubrieu-jpl** [comment]
Delayed because the ticket still need to be reviewed and merged.
