### ISSUE TITLE
Write procedure documentation

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#83]
While doing so, identify missing steps in the workflow.

For example we want Node to be able to update a DOI (in OSTI format), and the EN operator to validate and re-submit it.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams  will provide an example

**Comment by tloubrieu-jpl** [comment]
[Uploading DOI procedures.docx…]()

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @qchaupds can you review the draft procedure for EN operators ? It is in the comment above.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl Btw. here are some examples of ops procedures:

https://osr.jpl.nasa.gov/wiki/display/PDSEN/Operations+Procedures
https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process#engineering-node-process

**Comment by jordanpadams** [comment]
@tloubrieu-jpl doesn't look liek the upload worked?

**Comment by qchaupds** [comment]
@tloubrieu-jpl @jordanpadams The instruction mentioned 'spreadsheet' but it doesn't mention a CSV text format.  The 'reserve' command supports both.  The ordering of the columns are also important and should be emphasized as well.

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/pds-doi-service/input 117 % more DOI_Reserved_GEO_200318.csv
status,title,publication_date,product_type_specific,author_last_name,author_first_name,related_resource
Reserved,Laboratory Shocked Feldspars Collection #1,2020-03-11,PDS4 Collection,Johnson,J. R.,urn:nasa:pds:lab_shocked_feldspars::2.0
Reserved,Laboratory Shocked Feldspars Collection #2,2020-03-12,PDS4 Collection,Johnson_2,J2. R2.,urn:nasa:pds:lab_shocked_feldspars_2::2.0
Reserved,Laboratory Shocked Feldspars Collection #3,2020-03-12,PDS4 Collection,Johnson_3,J3. R3.,urn:nasa:pds:lab_shocked_feldspars_3::2.0
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/pds-doi-service/input 118 %

**Comment by qchaupds** [comment]
@tloubrieu-jpl @jordanpadams Forgot to mentioned that Thomas added PDS4 format as well to 'reserve 'action.  He may be more familiar with the verbiage.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams  @qchaupds  Here are the procedures,
1. general presentation and directions for Discipline Node: https://pds-engineering.jpl.nasa.gov/content/doi
2. procedure for EN operator: https://pds-engineering.jpl.nasa.gov/content/manage_dois

Thanks Qui for your feedback.

I kept the procedure as simple as possible and did not detailed alternative formats that are supported by the software but only the one we prefer the discipline node to use. The alternative are documented in the software documentation. Does that make sense ?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl this is fine for now, since we will hopefully replace https://pds-engineering.jpl.nasa.gov/content/doi with a form down the road. As a node person looking at this page, it is a lot of information instead of something succinct, but I think that work will be done out of the DOI working group anyways.

Also, this page doesn't seem to work? https://pds-engineering.jpl.nasa.gov/content/manage_dois . You may have not clicked publish or save at the bottom after you completed putting it online

**Comment by tloubrieu-jpl** [comment]
@jordanpadams sorry I think you looked at the previous version (since my changes were rolled back). They are available now.

1) The DN procedures could still have a shorter version.
2) manage_doi link works.
3) I need to add an index at the top of the pages

**Comment by jordanpadams** [comment]
@tloubrieu-jpl comments:
* For reserve step, can we link to the Excel template 
* Can we number the steps to the procedure?

> The produced OSTI DOI label can be updated by the Discipline Node Requestor or the Engineering Node Operator in a review step (e.g. by email).

Can we be explicit here? e.g. send email to node to review the metadata.

* Per the draft and review, and submit the DOI sections, can we make this more of an explicit step-by-step procedure?
