### ISSUE TITLE
feature updates or questions while writing the operator procedure

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-doi-service#95]
for reserve, spreadsheet format do we need:
- the column status (since it is always 'reserved')
- the PDS4 prefix in the product_specific_type
- submitter email (since it is in the command line arguments)

for reserve, how do we manage multuple authors ? 

Could we name related_resource lidvid ?

**Comment by jordanpadams** [comment]
> for reserve, how do we manage multuple authors ?

do we care? this is just reserve, so its doesn't really matter, no?

> Could we name related_resource lidvid ?

Is this in the DOI metadata or something else?

**Comment by jordanpadams** [comment]
closing this ticket since it is unknown what the issue is. will re-open if future node user's identify an issue.
